package main

import (
	"database/sql"
	"fmt"
	"strings"
	"time"
)

// generateStandup returns a markdown standup update using yesterday's and
// today's summarized blocks. It relies on the existing block summaries rather
// than making another AI call, so it is fast and costs nothing.
func generateStandup(db *sql.DB, cfg Config, asJSON bool) (string, map[string]any, error) {
	yesterday := time.Now().AddDate(0, 0, -1)
	today := time.Now()

	yBlocks, err := blocksForDay(db, yesterday, false)
	if err != nil {
		return "", nil, err
	}
	tBlocks, err := blocksForDay(db, today, false)
	if err != nil {
		return "", nil, err
	}

	yHighlights := standupHighlights(yBlocks)
	tHighlights := standupHighlights(tBlocks)

	if asJSON {
		if yHighlights == nil {
			yHighlights = []string{}
		}
		if tHighlights == nil {
			tHighlights = []string{}
		}
		out := map[string]any{
			"yesterday": map[string]any{
				"date":       yesterday.Format("2006-01-02"),
				"highlights": yHighlights,
			},
			"today": map[string]any{
				"date":       today.Format("2006-01-02"),
				"highlights": tHighlights,
			},
		}
		return "", out, nil
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Standup update\n\n**Yesterday** (%s):\n", yesterday.Format("Monday, Jan 2"))
	if len(yHighlights) == 0 {
		b.WriteString("_No summarized activity._\n")
	} else {
		for _, h := range yHighlights {
			fmt.Fprintf(&b, "- %s\n", h)
		}
	}
	fmt.Fprintf(&b, "\n**Today so far** (%s):\n", today.Format("Monday, Jan 2"))
	if len(tHighlights) == 0 {
		b.WriteString("_No summarized activity yet._\n")
	} else {
		for _, h := range tHighlights {
			fmt.Fprintf(&b, "- %s\n", h)
		}
	}
	b.WriteString("\n**Blockers:**\n_What is in your way?_\n")
	b.WriteString("\n---\n_Generated by dayflow_\n")
	return b.String(), nil, nil
}

func standupHighlights(blocks []Block) []string {
	if len(blocks) == 0 {
		return nil
	}
	var out []string
	for _, c := range mergeCards(blocks) {
		if c.Category == "idle" || c.Title == "No activity" {
			continue
		}
		app := ""
		if c.App != "" {
			app = fmt.Sprintf(" @%s", appDisplayName(c.App))
		}
		if c.Blocks > 1 {
			out = append(out, fmt.Sprintf("%s–%s — %s (%s, %s, %d blocks)%s",
				c.StartStr, c.EndStr, c.Title, catDisplay(c.Category), fmtDur(c.Minutes), c.Blocks, app))
		} else {
			out = append(out, fmt.Sprintf("%s–%s — %s (%s, %s)%s",
				c.StartStr, c.EndStr, c.Title, catDisplay(c.Category), fmtDur(c.Minutes), app))
		}
	}
	return out
}
