package main

import (
	"database/sql"
	"fmt"
	"sort"
	"strings"
	"time"
)

// StandupEntry is one aggregated line of a standup: all the day's merged
// cards for the same app + category folded into a single duration-ranked row.
type StandupEntry struct {
	Title      string `json:"title"`
	Minutes    int    `json:"minutes"`
	Category   string `json:"category"`
	App        string `json:"app"`
	Span       string `json:"span"`
	Productive bool   `json:"productive"`
}

// generateStandup returns a markdown standup update using yesterday's and
// today's summarized blocks. It relies on the existing block summaries rather
// than making another AI call, so it is fast and costs nothing.
func generateStandup(db *sql.DB, cfg Config, asJSON bool) (string, map[string]any, error) {
	yesterday := time.Now().AddDate(0, 0, -1)
	today := time.Now()

	yBlocks, err := blocksForDay(db, yesterday, false)
	if err != nil {
		return "", nil, err
	}
	tBlocks, err := blocksForDay(db, today, false)
	if err != nil {
		return "", nil, err
	}

	yEntries, yTotal := standupEntries(yBlocks)
	tEntries, tTotal := standupEntries(tBlocks)

	if asJSON {
		if yEntries == nil {
			yEntries = []StandupEntry{}
		}
		if tEntries == nil {
			tEntries = []StandupEntry{}
		}
		out := map[string]any{
			"yesterday": map[string]any{
				"date":          yesterday.Format("2006-01-02"),
				"total_minutes": yTotal,
				"entries":       yEntries,
			},
			"today": map[string]any{
				"date":          today.Format("2006-01-02"),
				"total_minutes": tTotal,
				"entries":       tEntries,
			},
		}
		return "", out, nil
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Standup update\n\n**Yesterday** (%s) — %s tracked:\n",
		yesterday.Format("Monday, Jan 2"), fmtDur(yTotal))
	if len(yEntries) == 0 {
		b.WriteString("_No summarized activity._\n")
	} else {
		for _, e := range yEntries {
			fmt.Fprintf(&b, "- **%s** — %s\n", fmtDur(e.Minutes), standupLabel(e))
		}
	}
	fmt.Fprintf(&b, "\n**Today so far** (%s) — %s tracked:\n",
		today.Format("Monday, Jan 2"), fmtDur(tTotal))
	if len(tEntries) == 0 {
		b.WriteString("_No summarized activity yet._\n")
	} else {
		for _, e := range tEntries {
			fmt.Fprintf(&b, "- **%s** — %s\n", fmtDur(e.Minutes), standupLabel(e))
		}
	}
	b.WriteString("\n**Blockers:**\n_What is in your way?_\n")
	b.WriteString("\n---\n_Generated by dayflow_\n")
	return b.String(), nil, nil
}

func standupLabel(e StandupEntry) string {
	parts := []string{}
	if e.App != "" {
		parts = append(parts, e.App)
	}
	parts = append(parts, catDisplay(e.Category))
	return fmt.Sprintf("%s (%s)", e.Title, strings.Join(parts, " · "))
}

// standupEntries folds the day's merged cards into app+category groups and
// returns them ranked by total minutes, along with tracked minutes overall.
func standupEntries(blocks []Block) ([]StandupEntry, int) {
	if len(blocks) == 0 {
		return nil, 0
	}
	type group struct {
		entry    StandupEntry
		bestMins int
	}
	groups := map[string]*group{}
	total := 0
	for _, c := range mergeCards(blocks) {
		if c.Category == "idle" || c.Title == "No activity" {
			continue
		}
		total += c.Minutes
		app := c.AppName
		if app == "" {
			app = appDisplayName(c.App)
		}
		key := app + "|" + c.Category
		g, ok := groups[key]
		if !ok {
			g = &group{entry: StandupEntry{Category: c.Category, App: app}}
			groups[key] = g
		}
		g.entry.Minutes += c.Minutes
		if c.Productive {
			g.entry.Productive = true
		}
		if c.Minutes >= g.bestMins {
			g.bestMins = c.Minutes
			g.entry.Title = c.Title
			g.entry.Span = c.StartStr + "–" + c.EndStr
		}
	}
	out := make([]StandupEntry, 0, len(groups))
	for _, g := range groups {
		out = append(out, g.entry)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Minutes > out[j].Minutes })
	return out, total
}
