#!/usr/bin/env python3
"""Offscreen layout verification for the classic compact popup.

Builds an isolated Quickshell package under a temp root — repo *.qml symlinked
in, inert qs.Commons/qs.Ui stubs replacing the shell modules, and a fail-closed
`dayflow` binary on PATH answering the commands the surfaces spawn with canned
JSON (DAYFLOW_CONFIG/DAYFLOW_DATA_DIR are exported so no invocation can touch
the real store). Runs `quickshell --path root` offscreen; failures print as
FIT_FAIL / binding errors and the run exits nonzero.
"""

import os
import re
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SHELL = Path.home() / ".local/share/omarchy/shell"

STYLE_STUB = """\
// Auto-generated by tests/ui/verify-fit.py — values scraped from the live
// Omarchy theme so renders match production geometry.
pragma Singleton
import QtQuick
QtObject {
  readonly property int rounding: %(rounding)d
  readonly property int cornerRadius: %(rounding)d
  readonly property string fontFamilyMonospace: "%(mono)s"
  readonly property string fontFamilyInterface: "%(ui)s"
  readonly property int fontMonospaceSize: %(monopx)d
  readonly property int fontInterfaceSize: %(uipx)d
  readonly property int barHeight: 30

  function space(n) { return Math.round(n) }
  function fontPx(scale) { return %(uipx)d * scale }
  function font(weight) { switch (weight) {
    case "bold": return Font.DemiBold
    case "medium": return Font.Medium
    case "demibold": return Font.DemiBold
    case "light": return Font.Light
    default: return Font.Normal } }
  function monoPx() { return %(monopx)d }
  function textPx() { return %(uipx)d }
  function px(scale) { return %(uipx)d * scale }

  readonly property QtObject font: QtObject {
    readonly property int caption: %(uipx)d
    readonly property int body: %(uipx)d + 1
    readonly property int section: %(uipx)d + 2
    readonly property int subtitle: %(uipx)d + 3
    readonly property int title: %(uipx)d + 4
    readonly property int display: %(uipx)d + 8
    readonly property int barHeight: 26
    readonly property int panelHeader: %(uipx)d + 2
  }
}
"""

COLOR_STUB = """\
// Auto-generated by tests/ui/verify-fit.py — colors.toml surface values.
pragma Singleton
import QtQuick
QtObject {
  readonly property color background: "%(background)s"
  readonly property color foreground: "%(foreground)s"
  readonly property color primary: "%(primary)s"
  readonly property color accent: "%(primary)s"
  readonly property color surface0: "%(surface0)s"
  readonly property color surface1: "%(surface1)s"
  readonly property color surface2: "%(surface2)s"
  readonly property color border0: "%(border0)s"
  readonly property color border1: "%(border1)s"
  readonly property color error: "%(error)s"
  readonly property color warning: "%(warning)s"
  readonly property color ok: "%(ok)s"
  readonly property color muted: "%(muted)s"
}
"""

KEYBOARD_PANEL_STUB = """\
// Auto-generated by tests/ui/verify-fit.py — renders the popup as a plain
// Item offscreen; ignores anchoring/focus/chrome that need a live compositor.
// fittedContent* mirror the real KeyboardPanel's desired-vs-cap contract
// with no screen cap (offscreen, nothing to collide with).
import QtQuick
Item {
  property var anchorItem
  property var owner
  property var bar
  property bool open: true
  property var focusTarget
  property int contentWidth: 100
  property int contentHeight: 100
  width: contentWidth
  height: contentHeight
  function fittedContentWidth(width, cap) { return Math.round(Math.max(1, Number(width) || 1)) }
  function fittedContentHeight(h, cap) { return Math.round(Math.max(1, Number(h) || 1)) }
  function cappedContentHeight(h) { return fittedContentHeight(h) }
}
"""

QMLOUTER = lambda members: (
    "module qs.Ui\n"
    + "".join(f"{name} 1.0 {name}.qml\n" for name in members)
)

DAYFLOW_STUB = """\
#!/bin/sh
# Canned dayflow for the offscreen fit harness. Fail-closed: any invocation
# not mapped here exits 2 so a surface calling something real fails loudly
# instead of silently rendering with missing data.
echo "$*" >> "${DAYFLOW_STUB_LOG:-/dev/null}"
case "$1" in
  status)
    printf '%s\\n' '{"paused":false,"configured":true,"model":"stub-1b","active_app":"code","ignored_apps":["obsidian"],"frames_today":120,"blocks_pending":3,"storage_text":"32 MB","version":"1.6.0","panel_expanded":false}' ;;
  timeline)
    printf '%s\\n' '{"date":"2026-10-09","blocks":[],"cards":[
      {"kind":"activity","title":"dayflow polish","category":"dev","productive":true,"blocks":12,"app_name":"Ghostty","start":"08:00","end":"11:00","children":[{"start_ts":1760000000,"end_ts":1760010800}]},
      {"kind":"activity","title":"review","category":"communication","productive":true,"blocks":4,"app_name":"Slack","start":"11:00","end":"12:00","children":[{"start_ts":1760010800,"end_ts":1760014400}]}
    ]}' ;;
  day)
    printf '%s\\n' '{"date":"2026-10-09","slot_minutes":15,"total_minutes":480,"slots":[],"categories":[]}' ;;
  standup)
    case "$2" in
      --json) printf '%s\\n' '{"yesterday":{"date":"2026-10-08","total_minutes":300,"entries":[]},"today":{"date":"2026-10-09","total_minutes":120,"entries":[]},"draft":{"date":"2026-10-09","highlights":"","tasks":"","blockers":"","priorities":""}}' ;;
      *) printf 'ok\\n' ;;
    esac ;;
  goal)
    case "$2" in
      set) printf 'ok\\n' ;;
      *) printf '%s\\n' '{"date":"2026-10-09","goal":"ship classic polish","completed":false}' ;;
    esac ;;
  insights)
    printf '%s\\n' '{"total_minutes":1200,"focus_minutes":700,"distraction_minutes":200,"idle_minutes":100,"categories":[],"apps":[],"top_distractions":[],"focus_blocks":[],"days":5}' ;;
  week)
    printf '%s\\n' '{"blocks":[],"cards":[]}' ;;
  review)
    printf '%s\\n' '{"review":"A solid week."}' ;;
  weekly)
    printf '%s\\n' '{"start":"2026-10-05","end":"2026-10-11","total_minutes":1200,"focus_minutes":700,"distraction_minutes":200,"idle_minutes":100,"category_donut":[],"app_treemap":[],"context_shifts":[],"context_shift_count":0,"top_distractions":[],"focus_blocks":[],"highlights":[],"suggestions":[],"heatmap":[]}' ;;
  config)
    case "$2" in
      --json) printf '%s\\n' '{"provider":"local","model":"gemma3:4b","api_base_url":"http://localhost:11434/v1","api_key":"","frames_dir":"/tmp/fit-data/frames","capture_interval":30,"capture_quality":70,"capture_scale":0.5,"day_start_hour":6,"blocked_apps":[],"ignored_apps":["obsidian"],"context_shift_min_gap_minutes":10,"context_shift_min_switch_seconds":45,"classification_prompt":"","knowledge_sync":false,"knowledge_sync_interval":60,"agent_recaps":true,"agent_sources":[],"notify_on_shift":false,"week_start":1}' ;;
      *) printf 'ok\\n' ;;
    esac ;;
  models)
    printf '%s\\n' '[{"name":"gemma3:4b","slug":"local/gemma3:4b","notes":"local"},{"name":"qwen3-vl:8b","slug":"local/qwen3-vl:8b","notes":"local vision"}]' ;;
  provider)
    case "$2" in
      list) printf '%s\\n' '[{"id":"local","name":"Local (Ollama / OpenAI-compatible)","env":"","api_base_url":"","prompt_overrides":{}},{"id":"openrouter","name":"OpenRouter","env":"OPENROUTER_API_KEY","api_base_url":"","prompt_overrides":{}}]' ;;
      *) printf 'ok\\n' ;;
    esac ;;
  detect)
    printf '%s\\n' '{"ollama":true,"lmstudio":false,"ollama_models":["gemma3:4b","qwen3-vl:8b"],"lmstudio_models":[],"agents":{"claude":true,"codex":true,"devin":true},"presets":[{"id":"local","name":"Local","slug":"local/gemma3:4b","model":"gemma3:4b","api_base_url":"http://localhost:11434/v1"}]}' ;;
  briefing)
    printf '%s\\n' '{"day":"2026-10-09","generated_at":"2026-10-09T12:00:00Z","mode":"fallback","recaps_enabled":true,"workstreams":[],"sources":[{"source":"claude","sessions":0,"status":"empty"}]}' ;;
  conversations) printf '%s\\n' '[]' ;;
  conversation) printf '%s\\n' '{"messages":[],"provider":"local","model":"gemma3:4b"}' ;;
  chat) printf '%s\\n' '{"reply":"hi","provider":"local","model":"gemma3:4b"}' ;;
  forecast) printf '%s\\n' '{"predictions":[]}' ;;
  frames) printf '%s\\n' '[]' ;;
  playback) printf '%s\\n' '{"state":"idle"}' ;;
  doctor) printf '%s\\n' '{"ok":true,"checks":[{"name":"stub","ok":true}]}' ;;
  ignore) printf '%s\\n' '{"ignored":"code"}' ;;
  unignore) printf 'ok\\n' ;;
  edit|toggle|log|summarize|install|export|timelapse) printf 'ok\\n' ;;
  key) printf 'devin\\n' ;;
  *) exit 2 ;;
esac
"""


def toml_str(src: str, key: str, default: str) -> str:
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*\"([^\"]*)\"", src, re.M)
    return m.group(1) if m else default


def toml_int(src: str, key: str, default: int) -> int:
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\d+)", src, re.M)
    return int(m.group(1)) if m else default


def build(root: Path) -> None:
    for qml in ROOT.glob("*.qml"):
        (root / qml.name).symlink_to(qml)

    commons = root / "Commons"
    commons.mkdir()
    (commons / "qmldir").write_text(
        "module qs.Commons\n"
        "singleton Style 1.0 Style.qml\n"
        "singleton Color 1.0 Color.qml\n"
        "Settings 1.0 Settings.qml\n"
    )

    theme_dir = Path.home() / ".local/state/omarchy/current/theme"
    shell_toml = (theme_dir / "shell.toml").read_text() if (theme_dir / "shell.toml").exists() else ""
    colors_toml = (theme_dir / "colors.toml").read_text() if (theme_dir / "colors.toml").exists() else ""
    rounding = toml_int(shell_toml, "rounding", 9)
    if rounding == 9:  # try the hyprland decoration too
        hypr = Path.home() / ".local/state/omarchy/current/theme/hyprland.lua"
        if hypr.exists():
            m = re.search(r"rounding\s*=\s*(\d+)", hypr.read_text())
            if m:
                rounding = int(m.group(1))
    ui_px = toml_int(shell_toml, "font_interface_size", 12)
    mono_px = toml_int(shell_toml, "font_monospace_size", 12)
    mono = toml_str(shell_toml, "font_monospace_family", "monospace")
    ui = toml_str(shell_toml, "font_interface_family", "sans-serif")

    (commons / "Style.qml").write_text(STYLE_STUB % {
        "rounding": rounding, "mono": mono, "ui": ui,
        "monopx": mono_px, "uipx": ui_px,
    })
    (commons / "Color.qml").write_text(COLOR_STUB % {
        "background": toml_str(colors_toml, "background", "#1c2128"),
        "foreground": toml_str(colors_toml, "foreground", "#e8e6e3"),
        "primary": toml_str(colors_toml, "primary", "#6b8cae"),
        "surface0": toml_str(colors_toml, "surface0", "#22282f"),
        "surface1": toml_str(colors_toml, "surface1", "#262c34"),
        "surface2": toml_str(colors_toml, "surface2", "#2b323b"),
        "border0": toml_str(colors_toml, "border0", "#2e353d"),
        "border1": toml_str(colors_toml, "border1", "#37414c"),
        "error": toml_str(colors_toml, "error", "#d06b64"),
        "warning": toml_str(colors_toml, "warning", "#d9a94a"),
        "ok": toml_str(colors_toml, "ok", "#7fb069"),
        "muted": toml_str(colors_toml, "muted", "#8b8f95"),
    })
    # Minimal Settings singleton substitute — surfaces only check for
    # knowledge_sync, which our engine stub already answers via config.
    (commons / "Settings.qml").write_text(
        "import QtQuick\nQtObject {}\n"
    )

    ui_dir = root / "Ui"
    ui_dir.mkdir()
    # Real shell files that need no compositor; stub only the PanelWindow.
    for name in ["Panel", "PanelController", "PanelKeyCatcher", "PanelSeparator"]:
        (ui_dir / f"{name}.qml").symlink_to(SHELL / "Ui" / f"{name}.qml")
    (ui_dir / "KeyboardPanel.qml").write_text(KEYBOARD_PANEL_STUB)
    (ui_dir / "qmldir").write_text(QMLOUTER(
        ["Panel", "PanelController", "PanelKeyCatcher", "PanelSeparator", "KeyboardPanel"]))

    bindir = root / "bin"
    bindir.mkdir()
    stub = bindir / "dayflow"
    stub.write_text(DAYFLOW_STUB)
    stub.chmod(stub.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    outdir = root / "out"
    outdir.mkdir()
    fit = (ROOT / "tests/ui/fit.qml").read_text()
    (root / "shell.qml").write_text(
        fit.replace("OUTPUT_PATH", f'"{outdir}"')
    )


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="dayflow-fit-") as tmp:
        root = Path(tmp)
        build(root)
        env = dict(os.environ)
        env["PATH"] = f"{root / 'bin'}:{env['PATH']}"
        env["QT_QPA_PLATFORM"] = "offscreen"
        env["DAYFLOW_CONFIG"] = str(root / "config.json")
        env["DAYFLOW_DATA_DIR"] = str(root / "data")
        env["DAYFLOW_STUB_LOG"] = str(root / "dayflow-calls.log")
        proc = subprocess.run(
            ["quickshell", "--path", str(root)],
            env=env, capture_output=True, text=True, timeout=120,
        )
        sys.stdout.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        calls = (root / "dayflow-calls.log")
        if calls.exists():
            print("\n-- dayflow calls --")
            print(calls.read_text())
        shots = sorted(p.name for p in (root / "out").glob("*.png"))
        print(f"-- {len(shots)} screenshots in {root}/out (temp dir cleaned on exit) --")
        return proc.returncode


if __name__ == "__main__":
    sys.exit(main())
